/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of the AUTOSAR module Fls
 ** function Fls_Init.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]============================================*/

#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief Fls_InitLib
 **
 ** Initializes the FLS module (software) and all flash memory relevant registers (hardware).
 **
 ** \param[in]  ConfigPtr       Configuration address
 **
 ** \return     none
 */
FUNC(void, FLS_CODE) Fls_InitLib
(
    P2CONST(Fls_ConfigType, AUTOMATIC, FLS_APPL_CONST) ConfigPtr
)
{
    /* enter exclusive area */
    Fls_EnterCritiSec();

    /* Fls015: check configuration for consistence -> FLS_E_PARAM_CONFIG */
    /* check will be done in tresos */

    /*[FLS268] If DET is enabled, check FLS module state. Report FLS_E_BUSY*/
    /*if module state is MEMIF_BUSY.*/
    if( MEMIF_BUSY == Fls_DriverState )
    {
        /* exit exclusive area */
        Fls_ExitCritiSec();

        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_INIT,
                               FLS_E_BUSY );
    }
    /* set IPC structure for FLASH management API and flash interface status register address for each core */
    else if( Fls_SetCoreSpecificData() == FLS_FALSE )
    {
        /* exit exclusive area */
        Fls_ExitCritiSec();

        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_INIT,
                               FLS_E_PARAM_CONFIG );
    }
    /* set pointer to configuration */
    else if( Fls_SetConfig(ConfigPtr) == FLS_FALSE )
    {
        /* exit exclusive area */
        Fls_ExitCritiSec();

        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_INIT,
                               FLS_E_PARAM_CONFIG );
    }
    else
    {
        /* Fls014: initialize variables with given configuration */
        Fls_Mode = Fls_ConfigPtr->DefaultMode;    /* set default FLS mode */

        /* set the current cycle mode to MEMIF_MODE_SLOW */
        Fls_CycleMode = MEMIF_MODE_SLOW;

        /* Fls086: initialize variables independent of other (hardware) modules, e.g. driver state */
        Fls_JobRequest.CurrentJob = FLS_IDLE;         /* no job pending             */
        Fls_JobRequest.Fls_MainFunctionTime = FLS_MAX_TIME_INIT; /* clear Fls_MainFunctionTime */
        Fls_JobRequest.ReadWithoutBlankCheck = FLS_FALSE; /* unset flag for reading without blank check */
        Fls_IpcLocked = FLS_FALSE;            /* IPC structure used for safety mechanism is not locked */

        /* Fls324: set the job result to MEMIF_JOB_OK */
        Fls_JobResult   = MEMIF_JOB_OK;
        /* Fls323: set the driver state to MEMIF_IDLE */
        Fls_DriverState = MEMIF_IDLE;

        /* initialize suspended job */
        Fls_SuspendedJobRequest.CurrentJob            = FLS_IDLE;
        Fls_SuspendedJobRequest.Fls_MainFunctionTime  = FLS_MAX_TIME_INIT;
        Fls_SuspendedJobRequest.ReadWithoutBlankCheck = FLS_FALSE;

        /* Fls014: call initialization routine of flash driver engine */
        Fls_InitSub();

        /* exit exclusive area */
        Fls_ExitCritiSec();
    }

    return;
}

#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
