/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of the AUTOSAR module Fls
 ** internal data.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]============================================*/

#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

#define FLS_START_SEC_VAR_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief flash driver state */
VAR( MemIf_StatusType, FLS_VAR_INIT ) Fls_DriverState = MEMIF_UNINIT;

#define FLS_STOP_SEC_VAR_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

#define FLS_START_SEC_VAR_NO_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief job result of last job */
VAR( MemIf_JobResultType, FLS_VAR_NO_INIT ) Fls_JobResult;

/** \brief current flash mode */
VAR( MemIf_ModeType, FLS_VAR_NO_INIT ) Fls_Mode;

/** \brief holds data for the current job */
VAR( Fls_JobRequestType, FLS_VAR_NO_INIT ) Fls_JobRequest;

/** \brief holds data for verifing job */
VAR( Fls_WriteJobType, FLS_VAR_NO_INIT ) Fls_WriteGlobalJob;

/** \brief holds saved data for the suspended job */
VAR( Fls_JobRequestType, FLS_VAR_NO_INIT ) Fls_SuspendedJobRequest;

/** \brief holds saved data for suspended verifying job */
VAR( Fls_WriteJobType, FLS_VAR_NO_INIT ) Fls_WriteGlobalSuspendedJob;

/** \brief holds fault information */
VAR( Fls_FaultType, FLS_VAR_NO_INIT ) Fls_Fault;

/** \brief current cycle mode */
VAR( MemIf_ModeType, FLS_VAR_NO_INIT ) Fls_CycleMode;

/** \brief IPC structure for FLASH management API */
VAR( uint32, FLS_VAR_NO_INIT ) Fls_FMAPIIpcStruct;

/** \brief flash interface status register address */
volatile P2VAR( uint32, AUTOMATIC, FLS_APPL_DATA ) Fls_FlashStatusAddr;

/** \brief mask for reading safety mechanism IPC DATA0 register */
volatile VAR( uint32, FLS_VAR_NO_INIT ) Fls_EmbeddedListenMask;

#define FLS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
