/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of Fls sub module function
 ** Fls_GetStatusSub.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*========*/
/* Header */
/*========*/
#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */     


/*==================*/
/* function         */
/*==================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief Fls_GetStatusSub
**
** Get status of HAL.
**
** \return     status of HAL
** \retval     FLS_STATUS_IDLE        idle
** \retval     FLS_STATUS_WAIT_IDLE   waiting for idle
** \retval     FLS_STATUS_BUSY        busy
**
*/
FUNC(FLS_UCHAR, FLS_CODE) Fls_GetStatusSub
(
 void
)
{
    FLS_UCHAR retval;                   /* return value */
    
    switch(Fls_StateSub)
    {
    case FLS_HAL_WRITE:
    case FLS_HAL_WRITE_WAIT:
    case FLS_HAL_ERASE:
    case FLS_HAL_ERASE_WAIT:
        retval = FLS_STATUS_BUSY;
        break;
    case FLS_HAL_NOP:
        
        retval = Fls_PollingFlash();
        
        switch(retval)
        {
        case FLS_HAL_NOP:
            /* idle */
        case FLS_HAL_MAX:
            /* timeout */
            Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_DISABLE_INTERRUPT_WRITE ); /* disable interruption */
            Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_DISABLE_WRITE ); /* disable writing to flash memory */
            retval = FLS_STATUS_IDLE;
            Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_REFRESH_REGISTERS ); /* refresh registers */
            break;
        case FLS_FMC_ACT:
            /* waiting for idle */
            retval = FLS_STATUS_WAIT_IDLE;
            break;
        default:
            break;
        }
        break;
        
    default:
        /* Fls_StateSub is corruption */
        retval = FLS_STATUS_IDLE;
        break;
    }
    
    return retval;
}
#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[end of file]===========================================*/
