/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of the AUTOSAR module Fls
 ** function Fls_Write.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]============================================*/

#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>


/** \brief Fls_WriteLib
 **
 ** Setup of a flash write job to be processed when calling the MainFunction().
 ** The function Fls_Write shall copy the given parameters to Fls module internal
 ** variables, initiate a write job, set the FLS module status to MEMIF_BUSY,
 ** set the job result to MEMIF_JOB_PENDING and return with E_OK.
 **
 ** \param[in] TargetAddress    Target address in flash memory
 ** \param[in] SourceAddressPtr Pointer to source data buffer
 ** \param[in] Length           Number of bytes to write
 **
 ** \return    write command has been accepted/not been accepted
 ** \retval    E_NOT_OK         write command has not been accepted
 **            E_OK             write command has been accepted
 **
 */
FUNC(Std_ReturnType, FLS_CODE) Fls_WriteLib
(
    Fls_AddressType TargetAddress,
    P2CONST(uint8, AUTOMATIC, FLS_APPL_CONST) SourceAddressPtr,
    Fls_LengthType Length
)
{
    P2CONST(Fls_ConfigType, AUTOMATIC, FLS_APPL_CONST)      ConfigPtr;  /* Configuration address */
    P2CONST(Fls_MemoryMapType, AUTOMATIC, FLS_APPL_CONST)   MemoryMap;  /* Memory map address    */
    Fls_PhysicalAddressType PhysicalAddress;    /* physical address for write operation */
    Fls_PhysicalLengthType  LengthToSectorEnd;  /* calculated length to sector end */
    Fls_LengthType          MaxReadCurrentMode; /* max number of bytes to blank check */
    uint8                   Ret;                /* return value */

    /* initialize internal value */
    ConfigPtr = Fls_ConfigPtr;
    MemoryMap = Fls_MemoryMapPtr;

    /* Fls066: check that driver is initialized -> FLS_E_UNINIT, E_NOT_OK */
    if( Fls_DriverState == MEMIF_UNINIT )
    {
        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_WRITE,
                               FLS_E_UNINIT );

        /* set E_NOT_OK for return value  */
        Ret = E_NOT_OK;
    }
  
    /* Fls026: check that TargetAddress is valid -> FLS_E_PARAM_ADDRESS, E_NOT_OK */
    else if(
        ( TargetAddress >= ConfigPtr->TotalSize          ) ||
        (( TargetAddress & ( ConfigPtr->PageSize - 1UL )) != 0UL )
    )
    {
        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_WRITE,
                               FLS_E_PARAM_ADDRESS );

        /* set E_NOT_OK for return value  */
        Ret = E_NOT_OK;
    }

    /* Fls027: check that Length and TargetAddress + Length is valid -> FLS_E_PARAM_LENGTH,E_NOT_OK */
    else if(
            (( TargetAddress + Length )  >  ( ConfigPtr->TotalSize )) ||
            ( Length                  == 0UL                                 ) ||
            ((( TargetAddress + Length ) & ( ConfigPtr->PageSize - 1UL )) != 0UL )
    )
    {
        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_WRITE,
                               FLS_E_PARAM_LENGTH );

        /* set E_NOT_OK for return value  */
        Ret = E_NOT_OK;
    }
    /* Fls157: check SourceAddressPtr for not NULL -> FLS_E_PARAM_DATA, E_NOT_OK */
    /* check SourceAddressPtr is valid -> FLS_E_PARAM_DATA, E_NOT_OK             */
    else if( SourceAddressPtr == NULL_PTR )
    {
        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_WRITE,
                               FLS_E_PARAM_DATA );

        /* set E_NOT_OK for return value  */
        Ret = E_NOT_OK;
    }
    else
    {
        /* enter exclusive area */
        Fls_EnterCritiSec();

        /* Fls030: check that driver is not BUSY -> FLS_E_BUSY, E_NOT_OK */
        /* The command is not accepted if TargetAddress is within the range of sector used by suspended job. */
        /* Deviation from MISRA-C:2004 rule 12.4, MISRA-C:2012 Rule-13.5.
           Justification: This implementation is adopted for avoiding more nesting.
           It is no problem because side effects cannot be caused. */
        /* PRQA S 3415 4 */
        if( ( Fls_DriverState == MEMIF_BUSY ) ||
            ( ( Fls_SuspendedJobRequest.CurrentJob != FLS_IDLE ) &&
              ( Fls_GetLogicalSectorNumber( TargetAddress ) <= Fls_GetLogicalSectorNumber( Fls_SuspendedJobRequest.LogFlashAddress ) ) &&
              ( Fls_GetLogicalSectorNumber( Fls_SuspendedJobRequest.LogFlashAddress ) <= Fls_GetLogicalSectorNumber( ( TargetAddress + Length ) - 1UL ) ) )
        )
        {
            /* exit exclusive area */
            Fls_ExitCritiSec();

            /* report DET error */
            (void)Fls_ReportError( FLS_MODULE_ID,
                                   FLS_INSTANCE_ID,
                                   FLS_ID_WRITE,
                                   FLS_E_BUSY );

            /* set E_NOT_OK for return value  */
            Ret = E_NOT_OK;
        }
        else
        {
            MaxReadCurrentMode = ( Fls_Mode == MEMIF_MODE_SLOW ) ? ( ConfigPtr->MaxReadNormalMode ) : ( ConfigPtr->MaxReadFastMode );

            /* calculate physical address and length to sector end */
            Fls_ConvertLogicalFlashAddress( ConfigPtr,
                                            MemoryMap,
                                            TargetAddress,
                                            &PhysicalAddress,
                                            &LengthToSectorEnd);

            /* Fls331: copy given parameters internally, initiate a write job */
            /* Fls332: set driver state to MEMIF_BUSY */
            /* Fls333: set job result to MEMIF_JOB_PENDING */
            /* Deviation from MISRA-C:2004 rule 3.1, 11.3, MISRA-C:2012 Rule-11.4, Rule-11.6.
               Justification: This cast is needed for storing an address as an
               integral value for use of existing structure. */
            /* PRQA S 306 1 */
            Fls_JobRequest.RamAddress      = (Fls_AddressType)SourceAddressPtr;
            Fls_JobRequest.LogFlashAddress = TargetAddress;
            Fls_JobRequest.Length          = Length;
            Fls_JobRequest.ResetLength     = Length;

            Fls_JobRequest.CurrentLength = (( Length ) > ( LengthToSectorEnd )) ?
                                            ( LengthToSectorEnd ) : ( Length );

            Fls_JobResult                  = MEMIF_JOB_PENDING;
            Fls_DriverState                = MEMIF_BUSY;
            Fls_JobRequest.CurrentJob      = FLS_WRITE_PREVER_WAIT;

            /* update Fls_WriteGlobalJob */
            Fls_WriteGlobalJob.LogicalAddress = TargetAddress;
            Fls_WriteGlobalJob.CheckAreaSize  = Length;

            /* set Fls_MainFunctionTime to MainFunction time-limit for a write job */
            /* check the state of FlsSub  */
            Ret = Fls_GetStatusSub();
            if( Ret == FLS_STATUS_IDLE )
            {
                /* Deviation from MISRA-C:2004 rule 10.1, 10.3, MISRA-C:2012 Rule-10.4, Rule-10.7, Rule-10.8.
                   Justification: This implmentation is needed for doing a signed cast
                   to check under-flow for MainFunction time-limit. It is no problem
                   because the time-limit is always less than 0x7FFFFFFF. */
                /* PRQA S 1840,1860,1891,4394 1 */
                Fls_JobRequest.Fls_MainFunctionTime = FLS_MAX_TIME_WRITE;
            }
            else
            {
                /* Deviation from MISRA-C:2004 rule 10.1, 10.3, MISRA-C:2012 Rule-10.4, Rule-10.7, Rule-10.8.
                   Justification: This implmentation is needed for doing a signed cast
                   to check under-flow for MainFunction time-limit. It is no problem
                   because the time-limit is always less than 0x7FFFFFFF. */
                /* PRQA S 1840,1860,1891,4394 1 */
                Fls_JobRequest.Fls_MainFunctionTime = FLS_MAX_TIME_WRITE + FLS_MAX_TIME_SECTOR_ERASE;
            }

            /* exit exclusive area */
            Fls_ExitCritiSec();

            /* Fls334: set E_OK for return value  */
            Ret = E_OK;
        }
    }

    return Ret;
}

#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
