/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of Fls sub module function
 ** Fls_WriteSub.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*========*/
/* Header */
/*========*/
#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */     


/*==================*/
/* function         */
/*==================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief Fls_WriteSub
**
** Request for writing in flash memory.
**
** \param[in]  addr       start address to write
** \param[in]  data       data address
** \param[in]  length     length in byte
**
** \return     result of request
** \retval     FLS_REQUEST_ACCEPT     accept request
** \retval     FLS_REQUEST_DECLINE    decline request
** \retval     FLS_PARAMETER_ERROR    parameter error
**
*/
FUNC(FLS_UCHAR, FLS_CODE) Fls_WriteSub
(
 P2VAR(FLS_UCHAR, AUTOMATIC, FLS_APPL_DATA) addr,
 P2VAR(FLS_UCHAR, AUTOMATIC, FLS_APPL_DATA) data,
 FLS_ULONG length
)
{
    FLS_UCHAR retval;                   /* return value */
    
    /* save the parameter in internal variable for failsafe */
    Fls_ParamAddr   = addr;
    Fls_ParamLength = length;

    Fls_DataSize    = Fls_ParamLength;
    /* Deviation from MISRA-C:2004 rule 11.4, MISRA-C:2012 Rule-11.3.
       Justification: This cast is needed for handling with 32-bit type address. */
    /* PRQA S 310,3305 2 */
    Fls_NowAddr     = (FLS_ULONG *)Fls_ParamAddr;
    Fls_NowData     = (FLS_ULONG *)data;
    
    Fls_JobresultSub = FLS_JOB_PENDING;
    
    if( Fls_GetStatusSub() == FLS_STATUS_IDLE )
    {
        FLS_STATESUB_SET(FLS_HAL_WRITE)               /* set state */
        
        Fls_WriteFlashStart();
    }
    else
    {
        FLS_STATESUB_SET(FLS_HAL_WRITE_WAIT)          /* set state */
    }
    
    retval = FLS_REQUEST_ACCEPT;   /* accept request */
    
    return retval;
}

#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[end of file]===========================================*/
