#define BCAN_VERSION 
#define BCAN_VERSIONNUMBERINTERNAL 0
#define BCAN_VERSIONUMBER 240201
#define BCAN_VERSIONWEEK 1
#define BCAN_VERSIONYEAR 0
#define BCAN_VERSIONMONTH 1
#define BCAN_VERSIONDAY 1
