#define LOCALCAN_VERSION 
#define LOCALCAN_VERSIONNUMBERINTERNAL 0
#define LOCALCAN_VERSIONUMBER 108
#define LOCALCAN_VERSIONWEEK 1
#define LOCALCAN_VERSIONYEAR 0
#define LOCALCAN_VERSIONMONTH 1
#define LOCALCAN_VERSIONDAY 1
