/** \file Icu_Channel_SignalEdgeDetection.c
 **
 ** This file contains edge detect mode internal architecture function
 ** for the AUTOSAR Icu driver.
 **
 ** This file contains the implementation of the AUTOSAR module Icu
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 ** */

/*==================[inclusions]============================================*/
#include <Icu_Channel_SignalEdgeDetection.h>
#include <Icu_Internal.h>
#include <Icu_Resource.h>

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/
#define ICU_START_SEC_CODE_ASIL_B
#include <Icu_MemMap.h>

/** \brief Icu_EnableEdgeDetection_Internal
 **
 ** This function implements to enable the edge detection.
 **
 ** \param[in] ChannelPtr   Pointer to the channel configuration.
 ** \param[in] ChannelCtrl  Control the channel start or no start.
 **
 ** \return    None.
 **
 ** */
FUNC(void, ICU_CODE) Icu_EnableEdgeDetection_Internal
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,
  VAR(Icu_ChannelCtrlType, AUTOMATIC)                       ChannelCtrl
)
{
  P2VAR(Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA) ChExtStatePtr;
  P2CONST(Icu_drvFctTable_t, AUTOMATIC, ICU_APPL_CONST) FuncTablePtr = (*ChannelPtr->GetFuncTable)();
  /* Deviation from MISRA-C:2004 rule 11.4, MISRA-C:2012 Rule-11.5
     Justification: It is a necessary for Extension State access. */
  /* PRQA S 316 1 */
  ChExtStatePtr = (P2VAR(Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA)) ChannelPtr->ExtStatePtr;
  Icu_EnterCritiSec();

  /* Clear interrupt flags */
  FuncTablePtr->drvClearInterruptRequestFlag(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
  if (ChExtStatePtr->NotifyEnabled == TRUE)
  {
    FuncTablePtr->drvIsrEnable(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
  }
  /* When group start does not start trigger */
  if (ChannelCtrl == ICU_CHSTART)
  {
    /* Used by capture mode (Only use capture interrupt) */
    FuncTablePtr->drvStartCountTrigger(ChannelPtr);
  }
  /* Set running status */
  ChannelPtr->StatePtr->Status = ICU_RUNNING;
  /* Clear input state */
  ChExtStatePtr->InputStateIndex = 0U;
  ChExtStatePtr->InputState[0] = ICU_IDLE;
  ChExtStatePtr->InputState[1] = ICU_IDLE;

  Icu_ExitCritiSec();
}


/** \brief Icu_DisableEdgeDetection_Internal
 **
 ** This function implements to disable the edge detection.
 **
 ** \param[in] ChannelPtr   Pointer to the channel configuration.
 ** \param[in] ChannelCtrl  Control the channel stop or no stop.
 **
 ** \return    None.
 **
 ** */
FUNC(void, ICU_CODE) Icu_DisableEdgeDetection_Internal
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,
  VAR(Icu_ChannelCtrlType, AUTOMATIC)                       ChannelCtrl
)
{
  P2CONST(Icu_drvFctTable_t, AUTOMATIC, ICU_APPL_CONST) FuncTablePtr = (*ChannelPtr->GetFuncTable)();
  P2VAR(Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA) ChExtStatePtr;
  /* Deviation from MISRA-C:2004 rule 11.4, MISRA-C:2012 Rule-11.5
     Justification: It is a necessary for Extension State access. */
  /* PRQA S 316 1 */
  ChExtStatePtr = (P2VAR(Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA)) ChannelPtr->ExtStatePtr;

  Icu_EnterCritiSec();

  if (ChannelCtrl == ICU_CHSTOP)
  {
    /* Clear input trigger */
    FuncTablePtr->drvCtrlEnable(ChannelPtr, FALSE);
    FuncTablePtr->drvClearInputTrigger(ChannelPtr);
    FuncTablePtr->drvCtrlEnable(ChannelPtr, TRUE);
  }
  /* Disable interrupt */
  FuncTablePtr->drvIsrDisable(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
  /* Set STOPPED status */
  ChannelPtr->StatePtr->Status = ICU_STOPPED;
  /* Clear input state */
  ChExtStatePtr->InputStateIndex = 0U;
  ChExtStatePtr->InputState[0] = ICU_IDLE;
  ChExtStatePtr->InputState[1] = ICU_IDLE;

  Icu_ExitCritiSec();
}


/** \brief Icu_EdgeDetect_InterruptEvent
 **
 ** This function is the ISR of ICU for edge detection mode.
 **
 ** \param[in] ChannelPtr   Pointer to the channel configuration.
 ** \param[in] IntrFlag     Interrupt request flag of channel.
 ** \param[in] Mode         Icu wakeup mode, sleep or normal.
 **
 ** \return    None.
 ** */
FUNC(void, ICU_CODE) Icu_EdgeDetect_InterruptEvent
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,
  VAR(uint8, AUTOMATIC)                                     IntrFlag,
  VAR(Icu_ModeType, AUTOMATIC)                              Mode
)
{
  P2CONST(Icu_EdgeDetectExtensionConfigType, AUTOMATIC, ICU_APPL_CONST) ChExtCfgPtr;
  P2VAR  (Icu_EdgeDetectChannelStateType,    AUTOMATIC, ICU_APPL_DATA)  ChExtStatePtr;

  /* Deviation from MISRA-C:2004 rule 11.4, MISRA-C:2012 Rule-11.5
     Justification: It is a necessary for Extension Config and State access. */
  /* PRQA S 316 2 */
  ChExtCfgPtr = (P2CONST(Icu_EdgeDetectExtensionConfigType, AUTOMATIC, ICU_APPL_CONST)) ChannelPtr->ExtConfigPtr;
  ChExtStatePtr = (P2VAR (Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA)) ChannelPtr->ExtStatePtr;
  /* Check if valid interrupt is detected */
  if (0U != (ICU_INT_CAPTURE & IntrFlag))
  {
    if (ICU_RUNNING == ChannelPtr->StatePtr->Status)
    {

      ChExtStatePtr->InputState[ChExtStatePtr->InputStateIndex] = ICU_ACTIVE;

    }
    /* In sleep mode, wakeup channel (running or no-running) can call IcuSignalNotification,
       if it matchs condition  */
    if (((Mode == ICU_MODE_SLEEP) || (ChannelPtr->StatePtr->Status == ICU_RUNNING)) &&
        (ChExtStatePtr->NotifyEnabled == TRUE) && (ChExtCfgPtr->Notification != NULL_PTR))
    {
      ChExtCfgPtr->Notification();
    }
  }
}


/** \brief Icu_SetEdgeDetectNotification
 **
 ** This function implements to enable/disable the notification of a channel in edge detection mode.
 **
 ** \param[in] ChannelPtr Pointer to the channel configuration.
 ** \param[in] Noti       Value depended to set the notification state of the specified channel.
 ** \param[in] Mode       ICU_MODE_NORMAL or ICU_MODE_SLEEP
 **
 ** \return    None.
 ** */

FUNC(void, ICU_CODE) Icu_SetEdgeDetectNotification
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,
  VAR(boolean, AUTOMATIC)                                   Noti,
  VAR(Icu_ModeType, AUTOMATIC)                              Mode
)
{
  P2VAR(Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA) ChExtStatePtr;
  P2CONST(Icu_drvFctTable_t, AUTOMATIC, ICU_APPL_CONST) FuncTablePtr = (*ChannelPtr->GetFuncTable)();
  /* Deviation from MISRA-C:2004 rule 11.4, MISRA-C:2012 Rule-11.5
     Justification: It is a necessary for Extension State access. */
  /* PRQA S 316 1 */
  ChExtStatePtr = (P2VAR(Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA)) ChannelPtr->ExtStatePtr;

  if (ICU_MODE_NORMAL == Mode)
  {
    if ((ICU_RUNNING == ChannelPtr->StatePtr->Status) &&
        (TRUE == Noti)                                &&
        (FALSE == ChExtStatePtr->NotifyEnabled))
    {
      Icu_UpdateInputState(ChannelPtr);
      FuncTablePtr->drvClearInterruptRequestFlag(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
      FuncTablePtr->drvIsrEnable(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
    }
    else if ((ICU_RUNNING == ChannelPtr->StatePtr->Status) &&
             (FALSE == Noti)                               &&
             (TRUE == ChExtStatePtr->NotifyEnabled))
    {
      FuncTablePtr->drvIsrDisable(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
    }
    else
    {
      /* Do nothing */
    }
  }
  ChExtStatePtr->NotifyEnabled = Noti;
}


/* \brief Icu_GetEdgeDetectInputState
 **
 ** This function implements to get the input the state of a channel in edge detection mode.
 **
 ** \param[in] ChannelPtr   Pointer to the channel configuration.
 ** \param[in] Mode       ICU_MODE_NORMAL or ICU_MODE_SLEEP
 **
 ** \return    Input state type of a channel.since the last call of Icu_GetInputState() or Icu_Init().
 **            ICU_ACTIVE: An activation edge has been detected.
 **            ICU_IDLE: No activation edge has been detected 
 **
 ** */
FUNC(Icu_InputStateType, ICU_CODE) Icu_GetEdgeDetectInputState
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,
  VAR(Icu_ModeType, AUTOMATIC)                              Mode
)
{
  Icu_InputStateType InState_Internal;
  Icu_LowCountType idx;
  P2VAR(Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA) ChExtStatePtr;
  P2CONST(Icu_drvFctTable_t, AUTOMATIC, ICU_APPL_CONST) FuncTablePtr = (*ChannelPtr->GetFuncTable)();
  /* Deviation from MISRA-C:2004 rule 11.4, MISRA-C:2012 Rule-11.5
     Justification: It is a necessary for Extension State access. */
  /* PRQA S 316 1 */
  ChExtStatePtr = (P2VAR(Icu_EdgeDetectChannelStateType, AUTOMATIC, ICU_APPL_DATA)) ChannelPtr->ExtStatePtr;

  Icu_EnterCritiSec();

  if ((ICU_RUNNING == ChannelPtr->StatePtr->Status) &&
      (FALSE == ChExtStatePtr->NotifyEnabled) &&
      (ICU_MODE_NORMAL == Mode))
  {
    /* Update input state */
    Icu_UpdateInputState(ChannelPtr);
    /* Clear INTR register */
    FuncTablePtr->drvClearInterruptRequestFlag(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
  }
  idx = ChExtStatePtr->InputStateIndex;
  ChExtStatePtr->InputStateIndex ^= 0x01u; /* index for double buffering to avoid effect described at (1) */
  /* return input state of the channel */
  InState_Internal = ChExtStatePtr->InputState[idx];
  /* (1) if an interrupt is detected here the captured time is cleared at (2) */
  /* reset input state to ICU_IDLE for detection of next edge */
  ChExtStatePtr->InputState[idx] = ICU_IDLE; /* (2) clear captured time for next service call */

  Icu_ExitCritiSec();

  return InState_Internal;
}


#define ICU_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Icu_MemMap.h>
/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
