#ifndef DIO_INTERNAL_H
#define DIO_INTERNAL_H

/** \brief AUTOSAR Dio DIO Driver
 **
 ** This file defines interface of internal function of Dio driver.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2020, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]=============================================*/
#include <Dio_Types.h>         /* DIO driver types */
#include <Dio_Version.h>       /* version check */

/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/*==================[internal constants]=====================================*/

/*==================[external function declarations]=========================*/

/* some toolchains really need this memory abstraction */
#define DIO_START_SEC_CODE_ASIL_B
#include <Dio_MemMap.h>

/** \brief Dio_ReadChannel_Internal
 **
 ** This function returns the value of the specified DIO channel.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     Channel level.
 **             STD_HIGH:The physical level of the corresponding Pin is high.
 **             STD_LOW:The physical level of the corresponding Pin is low.
 ** */
extern FUNC(Dio_LevelType, DIO_CODE) Dio_ReadChannel_Internal(
    Dio_ChannelType ChannelId,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
    );

/** \brief Dio_WriteChannel_Internal
 **
 ** This function write the value of the specified DIO channel.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 ** \param[in]  Level      The value to write.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     none
 ** */
extern FUNC(void, DIO_CODE) Dio_WriteChannel_Internal(
    Dio_ChannelType ChannelId, Dio_LevelType Level,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
    );

/** \brief Dio_ReadPort_Internal
 **
 ** This function returns the value of the specified DIO port.
 **
 ** \param[in]  PortId  The ID of the DIO port.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     Level of all channels of that port.
 ** */
extern FUNC(Dio_PortLevelType, DIO_CODE) Dio_ReadPort_Internal(
    Dio_PortType PortId, 
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
    );

/** \brief Dio_WritePort_Internal
 **
 ** This function write the value of the specified DIO port.
 **
 ** \param[in]  PortId  The ID of the DIO port.
 ** \param[in]  Level   The value to write.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     none
 ** */
extern FUNC(void, DIO_CODE) Dio_WritePort_Internal(
    Dio_PortType PortId, Dio_PortLevelType Level,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
    );

/** \brief Dio_MaskedWritePort_Internal
 **
 ** This function write the masked value of the specified DIO port.
 **
 ** \param[in]  PortId  The ID of the DIO port.
 ** \param[in]  Level   The value to write.
 ** \param[in]  Mask    The value of mask.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     none
 ** */
extern FUNC(void, DIO_CODE) Dio_MaskedWritePort_Internal(
    Dio_PortType PortId, Dio_PortLevelType Level, Dio_PortLevelType Mask,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
    );

/** \brief Dio_ReadChannelGroup_Internal
 **
 ** This function returns the value of the specified DIO channel group.
 **
 ** \param[in]  ChannelGroupIdPtr  Pointer to Channel Group.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     Level of channel groups.
 ** */
extern FUNC(Dio_PortLevelType, DIO_CODE) Dio_ReadChannelGroup_Internal(
    P2CONST(Dio_ChannelGroupType, AUTOMATIC, DIO_CONST) ChannelGroupIdPtr,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
    );

/** \brief Dio_WriteChannelGroup_Internal
 **
 ** This function write the value of the specified DIO channel group.
 **
 ** \param[in]  ChannelGroupIdPtr  Pointer to Channel Group.
 ** \param[in]  Level   The value to write.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     none
 ** */
extern FUNC(void, DIO_CODE) Dio_WriteChannelGroup_Internal(
    P2CONST(Dio_ChannelGroupType, AUTOMATIC, DIO_CONST) ChannelGroupIdPtr,
    Dio_PortLevelType Level,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
    );

/** \brief Dio_FlipChannel_Internal
 **
 ** This function flip (change from 1 to 0 or from 0 to 1) the level 
 ** of a channel and return the level of the channel after flip.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     Channel level.
 **             STD_HIGH:The physical level of the corresponding Pin is high.
 **             STD_LOW:The physical level of the corresponding Pin is low.
 ** */
extern FUNC(Dio_LevelType, DIO_CODE) Dio_FlipChannel_Internal(
    Dio_ChannelType ChannelId,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
    );

/** \brief Dio_isValidChannel
 **
 ** This function checks the validity of a specified channel.
 **
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 ** \param[in]  ChannelId  The ID of the DIO channel.
 **
 ** \retval     Validity of a ChannelId.
 **             TRUE  : valid ChannelId.
 **             FALSE : invalid ChannelId.
 ** */
extern FUNC(boolean, DIO_CODE) Dio_isValidChannel(
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr,
    Dio_ChannelType ChannelId
    );

/** \brief Dio_isValidPort
 **
 ** This function checks the validity of a specified port.
 **
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 ** \param[in]  PortId  The ID of the DIO port.
 **
 ** \retval     Validity of a PortId.
 **             TRUE  : valid PortId.
 **             FALSE : invalid PortId.
 ** */
extern FUNC(boolean, DIO_CODE) Dio_isValidPort(
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr,
    Dio_PortType PortId
    );

/** \brief Dio_isValidChannelGroup
 **
 ** This function checks the validity of a specified channel group.
 **
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 ** \param[in]  ChannelGroupIdPtr  Pointer to Channel Group.
 **
 ** \retval     Validity of a channel group.
 **             TRUE  : valid channel group.
 **             FALSE : invalid channel group.
 ** */
extern FUNC(boolean, DIO_CODE) Dio_isValidChannelGroup(
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr,
    P2CONST(Dio_ChannelGroupType, AUTOMATIC, DIO_CONST) ChannelGroupIdPtr
    );

#define DIO_STOP_SEC_CODE_ASIL_B
#include <Dio_MemMap.h>
/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#endif /* DIO_INTERNAL_H */
/*==================[end of file]============================================*/
