#ifndef MCU_VERSION_H
# define MCU_VERSION_H 1

/** \brief AUTOSAR Mcu Driver
 **
 ** This file contains the declaration of the version of the AUTOSAR module Mcu
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]=============================================*/
#include <Mcu_Cfg.h>       /* Generated MCU driver config */

/*==================[macros]=================================================*/
/*------------------[AUTOSAR module identification]--------------------------*/

#ifdef MCU_MODULE_ID /* to prevent double declaration */
#  error MCU_MODULE_ID already defined
#else
#  define MCU_MODULE_ID 101U
#endif /* ifdef MCU_MODULE_ID) */

/*------------------[AUTOSAR vendor identification]--------------------------*/

#ifdef MCU_VENDOR_ID /* to prevent double declaration */
#  error MCU_VENDOR_ID is already defined
#else
#  define MCU_VENDOR_ID 66U
#endif /* ifdef MCU_VENDOR_ID */

#ifdef MCU_INSTANCE_ID /* to prevent double declaration */
#  error MCU_INSTANCE_ID is already defined
#else
#  define MCU_INSTANCE_ID 0U
#endif /* ifdef MCU_VENDOR_ID */

/*------------------[AUTOSAR specification version]--------------------------*/

#if (defined MCU_AR_RELEASE_MAJOR_VERSION) /* to prevent double declaration */
#  error MCU_AR_RELEASE_MAJOR_VERSION already defined
#else
#  define MCU_AR_RELEASE_MAJOR_VERSION 4U
#endif /* if (defined MCU_AR_RELEASE_MAJOR_VERSION) */


#if (defined MCU_AR_RELEASE_MINOR_VERSION) /* to prevent double declaration */
#  error MCU_AR_RELEASE_MINOR_VERSION already defined
#else
#  define MCU_AR_RELEASE_MINOR_VERSION 2U
#endif /* if (defined MCU_AR_RELEASE_MINOR_VERSION) */


#if (defined MCU_AR_RELEASE_REVISION_VERSION) /* to prevent double declaration */
#error MCU_AR_RELEASE_REVISION_VERSION already defined
#else
#  define MCU_AR_RELEASE_REVISION_VERSION 2U
#endif /* if (defined MCU_AR_RELEASE_REVISION_VERSION) */

/*------------------[AUTOSAR module version identification]------------------*/

#if (defined MCU_SW_MAJOR_VERSION) /* to prevent double declaration */
#  error MCU_SW_MAJOR_VERSION already defined
#else
#  define MCU_SW_MAJOR_VERSION  1U
#endif /* if (defined MCU_SW_MAJOR_VERSION) */

#if (defined MCU_SW_MINOR_VERSION) /* to prevent double declaration */
#  error MCU_SW_MINOR_VERSION already defined
#else
#  define MCU_SW_MINOR_VERSION  19U
#endif /* if (defined MCU_SW_MINOR_VERSION) */

#if (defined MCU_SW_PATCH_VERSION) /* to prevent double declaration */
#  error MCU_SW_PATCH_VERSION already defined
#else
#  define MCU_SW_PATCH_VERSION  MCU_GEN_SW_PATCH_VERSION
#endif /* if (defined MCU_SW_PATCH_VERSION) */

/*------------------[AUTOSAR module version identification]------------------*/
/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

# endif /* if !defined( MCU_VERSION_H ) */
/*==================[end of file]============================================*/
