
#ifndef WDG_CBK_H
#define WDG_CBK_H 1

/** \brief AUTOSAR Wdg Driver
 **
 ** This file contains all callbacks declarations of the AUTOSAR module Wdg.
 ** If only one watchdog module is used within the ASC this header might be used
 ** instead of the default Wdg_66_IA_Cbk.h header for declaring those callbacks.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2020, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]=============================================*/
/*==================[macros]=================================================*/
/*==================[Callbacks]==============================================*/
/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* ifndef WDG_CBK_H */
/*==================[end of file]============================================*/
