
#ifndef WDG_66_IA_DET_H
#define WDG_66_IA_DET_H 1

/** \brief AUTOSAR Wdg Driver
 **
 ** This file contains development error processing macros
 ** used by the library.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2020, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]=============================================*/

#include <Std_Types.h>          /* AUTOSAR standard types */

/*==================[macros]=================================================*/

#if defined ( WDG_66_IA_DEV_ERROR_DETECT )
#if ( WDG_66_IA_DEV_ERROR_DETECT == STD_ON )
#include <Det.h>

/** WDG instance id used for DET reports */
#define WDG_66_IA_INSTANCE_ID_DET 0u

/*
 * WDG_66_IA_DET_REPORTERROR()
 *
 * In development mode, this macro reports the indicated error to the
 * Development error tracer (Det). The parameters are:
 *  a -- API id
 *  e -- error id
 */
/* Deviation from MISRA-C:2004 rule 19.7, MISRA-C:2012 Dir-4.9
   Justification: In case of using in small processing, function-like macro is used. 
                  It improves readability. */
/* PRQA S 3453 2 */
#define WDG_66_IA_DET_REPORTERROR(a,e) \
    (void)Det_ReportError( WDG_66_IA_MODULE_ID, WDG_66_IA_INSTANCE_ID_DET, (a), (e))

#else
/*
 * WDG_66_IA_DET_REPORTERROR()
 *
 * In production mode the macro evaluates to nothing. No error is reported.
 *  a -- API id
 *  e -- error id
 */
#define WDG_66_IA_DET_REPORTERROR(a,e)

#endif /* #if ( WDG_66_IA_DEV_ERROR_DETECT == STD_ON ) */
#endif /* #if defined ( WDG_66_IA_DEV_ERROR_DETECT ) */

/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/

#define WDG_66_IA_START_SEC_CODE
#include <Wdg_66_IA_MemMap.h>

/** \brief Wdg_66_IA_ReportDetError
 **
 ** This function is used to report an error to the error handler and optionally
 ** to the DET in the Wdg module.
 **
 ** \param [in] ApiId   Id of the service that detected the error.
 ** \param [in] ErrorId   Id of the error that was detected.
 */
extern FUNC( void, WDG_CODE )
Wdg_66_IA_ReportDetError( VAR( uint8, AUTOMATIC ) ApiId, VAR( uint8, AUTOMATIC ) ErrorId );

#define WDG_66_IA_STOP_SEC_CODE
#include <Wdg_66_IA_MemMap.h>

/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* if !defined( WDG_66_IA_DET_H ) */
/*==================[end of file]============================================*/
