/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of the AUTOSAR module Fls
 ** function Fls_CoreForMcal.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]============================================*/

#include <Fls.h>                /* Fls Flash Driver header file */
#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

#define FLS_START_SEC_CONST_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/* flag whether the HSM (Hardware Security Module) is present or not */
CONST( uint8, FLS_CONST ) Fls_HsmPresent = FLS_HSM_PRESENT;

/* value of FAULT.MASK1: SOURCE=Bit51/52/53 is 1 */
CONST( uint32, FLS_CONST ) Fls_FaultStructMask1Value = FLS_FAULT_STRUCT_MASK1_ENABLE;

#define FLS_STOP_SEC_CONST_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

#define FLS_START_SEC_VAR_NO_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/* IPC structure context (on scratch) referred by FLASH Management API */
VAR(uint32, FLS_VAR_NO_INIT) Fls_IpcContext[4];

/* Data to be written that is passed to FLASH Management API */
volatile VAR(uint32, FLS_VAR_NO_INIT) Fls_WriteData;

#define FLS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief Fls_SetCoreSpecificData
**
** Sets the specific data for each core.
**
 ** \return    result of setting
 ** \retval    FLS_TRUE     succeeded
 ** \retval    FLS_FALSE    failed
**
*/
FUNC(uint8, FLS_CODE) Fls_SetCoreSpecificData(void)
{
    uint8       Ret;    /* return value */

    Ret = FLS_FALSE;

    /* set IPC structure for FLASH management API and flash interface status register address for each core */
    switch( Fls_GetMasterId() )
    {
    /* Deviation from MISRA-C:2004 rule 17.4, MISRA-C:2012 Rule-18.4.
       Justification: This cast is needed for doing pointer arithmetic. */
    /* PRQA S 488 11 */
    case FLS_IDENTITY_MS_CM4_CM7_0:
        Fls_FMAPIIpcStruct = 1UL;
        Fls_FlashStatusAddr = FLS_REG_FLASHC_CM4_CM7_0_STATUS_ADDR;
#if ( FLS_USE_SAFETY_MECHANISM == STD_ON )
        Fls_EmbeddedListenMask = FLS_EMBEDDED_CM4_CM7_0_WORK;
#endif /* if( FLS_USE_SAFETY_MECHANISM == STD_ON ) */
        Ret = FLS_TRUE;
        break;
    case FLS_IDENTITY_MS_CM7_1:
        Fls_FMAPIIpcStruct = 2UL;
        Fls_FlashStatusAddr = FLS_REG_FLASHC_CM7_1_STATUS_ADDR;
#if ( FLS_USE_SAFETY_MECHANISM == STD_ON )
        Fls_EmbeddedListenMask = FLS_EMBEDDED_CM7_1_WORK;
#endif /* if( FLS_USE_SAFETY_MECHANISM == STD_ON ) */
        Ret = FLS_TRUE;
        break;
    default:
        break;
    }

    return Ret;
}

#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
