/** \brief AUTOSAR SPI Driver
 **
 ** This file declares the derivate common functions.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2021, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

#ifndef SPI_COMMON_DER_H_INCLUDED
#define SPI_COMMON_DER_H_INCLUDED

/*==================[inclusions]============================================*/
#include <Spi_Types.h>
#include <Spi_Internal_Types.h>

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

#define SPI_START_SEC_CODE_ASIL_B
#include <Spi_MemMap.h>

/** \brief Spi_Com_GetDmaChannelRegPtr
 **
 ** Return the start address of the DMA register for the specified HW unit.
 **
 ** \return Pointer to start address of the DMA register.
 ** \param [in] HwUnit   Id of HW unit.
 ** \param [in] Factor   Specify the factor of the transmission or reception.
 **
 */
extern FUNC_P2VAR(volatile Spi_DmaChannelRegsType, REGSPACE, SPI_CODE) Spi_Com_GetDmaChannelRegPtr
(
  VAR(Spi_HWUnitType, AUTOMATIC) HwUnit,
  VAR(Spi_HwFactorType, AUTOMATIC) Factor
);

#define SPI_STOP_SEC_CODE_ASIL_B
#include <Spi_MemMap.h>

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

#endif /*!defined(SPI_COMMON_DER_H_INCLUDED)*/

/*==================[end of file]===========================================*/
