#ifndef DIO_TYPES_REG_H
#define DIO_TYPES_REG_H

/** \brief AUTOSAR Dio DIO Driver
 **
 ** This file defines the register type definition of Dio driver.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2020, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]=============================================*/
#include <Std_Types.h>         /* AUTOSAR standard types */
/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/*------------------------[Register definitions]-----------------------------*/
/** \brief GPIO Port Register(OUT/OUT_SET/OUT_CLR/IN/CFG) map structure
 **
 ** This structure is the GPIO Port Register(OUT/OUT_SET/OUT_CLR/IN/CFG) Map. 
 */

typedef struct
{
    uint32    GPIO_PRT_OUT;         /* GPIO_PRT.OUT     reguster */
    uint32    GPIO_PRT_OUT_CLR;     /* GPIO_PRT.OUT_CLR reguster */
    uint32    GPIO_PRT_OUT_SET;     /* GPIO_PRT.OUT_SET reguster */
    uint32    GPIO_PRT_OUT_INV;     /* GPIO_PRT.OUT_INV reguster */
    uint32    GPIO_PRT_IN;          /* GPIO_PRT.IN      reguster */
    uint32    reserve1[12];         /* reserved */
    uint32    GPIO_PRT_CFG;         /* GPIO_PRT.CFG     reguster */
    uint32    reserve2[14];         /* reserved */
} Dio_GpioPrtRegisterType;

/*----------------[Definition of type Dio_RegisterInfomartionType]-----------*/
/** \brief IO Port Register Information structure
 **
 ** This structure contains the information for IO Port register address.
 */
typedef struct
{
    volatile CONSTP2VAR(Dio_GpioPrtRegisterType, AUTOMATIC, REGSPACE) gpioPrtRegBaseAddrPtr;
                                                    /* GPIO_PRT base address */
} Dio_IORegisterInfoType;

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#endif /* DIO_TYPES_REG_H */
/*==================[end of file]============================================*/
